# Generated by Django 5.2.8 on 2025-12-03 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_refrigerado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('refrigerado', models.BooleanField(default=False)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('medida', models.CharField(choices=[('L', 'Litros'), ('KG', 'Kilogramos'), ('g', 'Gramos'), ('UD', 'Unidades'), ('ml', 'Mililitros')], max_length=2)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.ManyToManyField(through='app.IngredienteReceta', to='app.ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receta'),
        ),
    ]
