# Generated by Django 5.2.8 on 2025-11-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaingrediente'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
