# Generated by Django 5.2.8 on 2025-12-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientereceta',
            unique_together={('ingrediente', 'receta')},
        ),
    ]
