# Generated by Django 5.2.8 on 2025-12-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ingrediente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='categoria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaingrediente'),
        ),
    ]
