# Generated by Django 5.2.8 on 2025-12-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ingrediente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaingrediente'),
        ),
    ]
